on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/91b93742d7fa7e47372572185bc85833
          gist_title: Pr치ctica-13 Motor DC Infrarrojo 4550-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/4550/MotorDCInfrarrojo.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/e85df3beab10fd0dafed9f2bbb0d4302
          gist_title: Pr치ctica-13 Motor DC Infrarrojo 45K50-MikroC.c
          gist_description: Pr치cticas MikroC Pro for PIC
          github_file: Proyecto/45K50/MotorDCInfrarrojo.c
          file_encoding: WINDOWS-1252